apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapplicationfirewalls.metacontroller.glueops.dev
spec:
  group:  metacontroller.glueops.dev
  names:
    kind: WebApplicationFirewall
    plural: webapplicationfirewalls
    singular: webapplicationfirewall
    shortNames:
    - waf
    - wafs
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            type: object
            properties:
              domains:
                type: array
                items:
                  type: string
                  description: "Raw JSON string representation of the full AWS WAF WebACL definition"
              custom_certificate_secret_store_path:
                type: string
                description: "Raw JSON string representation of the full AWS WAF WebACL definition"
    subresources:
      status: {}
