apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapplicationfirewalls.metacontroller.glueops.dev
spec:
  group:  metacontroller.glueops.dev
  names:
    kind: WebApplicationFirewall
    plural: webapplicationfirewalls
    singular: webapplicationfirewall
    shortNames:
    - waf
    - wafs
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            type: object
            properties:
              domains:
                type: array
                items:
                  type: string
                  description: "List of domains we want to have on the cert. This should include the TLD and any subdomains. Wildcards are also allowed."
              web_acl_name:
                type: string
                description: "Optional. Firewall Rules/Web ACL to enforce. You must have first deployed a WebApplicationFirewallWebACL resource."
              custom_certificate_secret_store_path:
                type: string
                description: "Optional. If you want to use a certificate instead of using one from AWS please feel free to import your own from vault. Ex. secret/ssl-antoniostacos.com"
    subresources:
      status: {}
